
--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender AS Gender,
CAST(SUM(CAST(purchase_amount AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS Revenue 
FROM customer_shopping_behavior 
GROUP BY gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,
CAST(purchase_amount AS DECIMAL(10,2)) AS purchase_amount 
FROM customer_shopping_behavior 
WHERE discount_applied='Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_shopping_behavior);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 item_purchased,
ROUND(AVG(review_rating),2) AS Review_Rating 
FROM customer_shopping_behavior 
GROUP BY item_purchased 
ORDER BY AVG(review_rating) DESC;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type,
CAST(AVG(CAST(purchase_amount AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS purchase_amount 
FROM customer_shopping_behavior 
WHERE shipping_type IN ('Standard','Express') 
GROUP BY shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) AS Total_Customer,
CAST(AVG(CAST(purchase_amount AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS Average_Spend,
CAST(SUM(CAST(purchase_amount AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS Revenue
FROM customer_shopping_behavior  
GROUP BY subscription_status;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased,
CAST(100 * SUM(CAST(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END AS DECIMAL(10,2)))/COUNT(*) AS DECIMAL(10,2))  AS Discount_Rate
FROM customer_shopping_behavior 
GROUP BY item_purchased 
ORDER BY Discount_Rate DESC;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH Customer_Segment AS (SELECT customer_id,
                                 previous_purchases, 
                                 CASE WHEN previous_purchases <= 1 THEN 'New'
			                          WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			                          ELSE 'Loyal' END AS Segment
                          FROM customer_shopping_behavior)
SELECT Segment, 
COUNT(*) AS Total_Customers
FROM Customer_Segment
GROUP BY Segment;


--Q8. What are the top 3 most purchased products within each category? 
WITH ItemCounts AS (
    SELECT category, 
    item_purchased,
    COUNT(customer_id) AS Purchase_Count,
    ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS RowNum
    FROM customer_shopping_behavior
    GROUP BY category, item_purchased
)
SELECT category, 
item_purchased, 
Purchase_Count
FROM ItemCounts
WHERE RowNum <= 3
ORDER BY category, RowNum;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT CASE WHEN subscription_status='Yes' THEN 'Subscription Customer' ELSE 'Non-Subscription Customer' END AS subscription_status,
COUNT(customer_id) AS RepeatCustomer
FROM customer_shopping_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;


--Q10. What is the revenue contribution of each age group? 
SELECT age_group,
SUM(purchase_amount) AS Revenue 
FROM customer_shopping_behavior
GROUP BY age_group 
ORDER BY Revenue DESC;









